# Generated by Django 5.1.4 on 2024-12-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='employees_KC',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='employees_UPP',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
