# Generated by Django 5.1.4 on 2024-12-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_record_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
