# Generated by Django 4.1.1 on 2024-12-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('coming', '0001_initial'),
        ('leads', '0004_alter_record_in_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coming.coming'),
            preserve_default=False,
        ),
    ]
