# Generated by Django 4.1.1 on 2024-12-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('coming', '0001_initial'),
        ('leads', '0006_alter_record_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='reporter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Record', to='coming.coming'),
        ),
    ]
