# Generated by Django 4.1.1 on 2024-12-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('coming', '0001_initial'),
        ('leads', '0007_alter_record_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='reporter',
        ),
        migrations.AddField(
            model_name='record',
            name='coming',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Record', to='coming.coming'),
        ),
    ]