# Generated by Django 4.1.1 on 2024-12-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_record_reporter_record_coming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='coming',
        ),
    ]
