# Generated by Django 5.1.4 on 2024-12-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_record_coming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='employees_KC',
            field=models.CharField(default='Не прикреплен', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='employees_UPP',
            field=models.CharField(default='Не прикреплен', max_length=50),
        ),
    ]
