# Generated by Django 5.1.4 on 2025-01-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_record_description_alter_record_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at']},
        ),
    ]
