# Generated by Django 5.1.4 on 2025-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_record_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='caunt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
