# Generated by Django 5.1.4 on 2025-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_record_caunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='caunt',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
