# Generated by Django 5.1.4 on 2025-01-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_record_caunt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('status', models.CharField(default='Новая', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('caunt', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('employees_KC', models.CharField(default='Не прикреплен', max_length=50)),
                ('employees_UPP', models.CharField(default='Не прикреплен', max_length=50)),
                ('in_work', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical record',
                'verbose_name_plural': 'historical records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
        ),
    ]
