# Generated by Django 5.1.4 on 2025-01-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_remove_cost_record'),
        ('leads', '0017_remove_historicalrecord_caunt_remove_record_caunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecord',
            name='cost',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cost.cost'),
        ),
        migrations.AddField(
            model_name='record',
            name='cost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cost.cost'),
        ),
    ]
