# Generated by Django 5.1.4 on 2025-01-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_historicalrecord_cost_record_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='record',
            name='cost',
        ),
    ]
