# Generated by Django 5.1.4 on 2025-02-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_historicalrecord_where_record_where'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRecord',
        ),
    ]
