# Generated by Django 5.1.4 on 2025-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_record_felial_alter_record_companys'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
