# Generated by Django 5.1.4 on 2025-03-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_record_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='employees_KC',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='employees_UPP',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
