# Generated by Django 5.1.4 on 2025-03-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('felial', '0001_initial'),
        ('leads', '0025_alter_record_employees_kc_alter_record_employees_upp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='companys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
        migrations.AlterField(
            model_name='record',
            name='employees_KC',
            field=models.CharField(default='Не прикреплённ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='employees_UPP',
            field=models.CharField(default='Не прикреплённ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='felial',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='felial.felial'),
        ),
    ]
