# Generated by Django 5.1.4 on 2025-04-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_record_companys_alter_record_employees_kc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='doc',
            field=models.URLField(null=True),
        ),
    ]
