# Generated by Django 5.1.4 on 2025-05-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('felial', '0001_initial'),
        ('leads', '0027_record_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='companys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
        migrations.AlterField(
            model_name='record',
            name='felial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='felial.felial'),
        ),
    ]
