# Generated by Django 5.1.4 on 2025-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_alter_record_companys_alter_record_felial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(default='Неизвестен', max_length=50, null=True),
        ),
    ]
