# Generated by Django 5.1.4 on 2026-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='employees_REP',
            field=models.CharField(default='Не прикреплённ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='representative',
            field=models.BooleanField(default=False),
        ),
    ]
