# Generated by Django 5.1.4 on 2026-02-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_record_employees_rep_record_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.record')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
