# Generated by Django 5.1.4 on 2026-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_recorddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='work_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
