# Generated by Django 5.1.4 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0032_record_work_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="work_comment_kc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="record",
            name="work_comment_op",
            field=models.TextField(blank=True, default=""),
        ),
    ]
