# Generated by Django 5.1.4 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0033_record_work_comment_kc_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="social_links",
            field=models.TextField(blank=True, default=""),
        ),
    ]
