# Generated by Django 5.1.4 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_record_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='paid_online',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Paid Online'),
        ),
    ]
