# Generated by Django 5.1.4 on 2026-06-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_alter_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
