# Generated by Django 5.1.4 on 2025-03-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('felial', '0001_initial'),
        ('smart_calendar', '0002_booking_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='companys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
        migrations.AddField(
            model_name='booking',
            name='felial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='felial.felial'),
        ),
    ]
