# Generated by Django 5.1.4 on 2025-03-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_record_companys_alter_record_employees_kc_and_more'),
        ('smart_calendar', '0003_booking_companys_booking_felial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='come',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.record'),
        ),
    ]
