# Generated by Django 5.1.4 on 2025-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_calendar', '0004_booking_come_alter_booking_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
