# Generated by Django 5.1.4 on 2025-03-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_calendar', '0006_booking_registering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='registering',
        ),
    ]
