# Generated by Django 5.1.4 on 2025-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_calendar', '0008_booking_registrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='come',
            field=models.IntegerField(null=True),
        ),
    ]
