# Generated by Django 5.1.4 on 2025-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_calendar', '0011_alter_booking_come'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='come',
            field=models.BooleanField(),
        ),
    ]
