# Generated by Django 5.1.4 on 2026-03-09 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companys_telegram_bot'),
        ('felial', '0001_initial'),
        ('leads', '0032_record_work_comment'),
        ('smart_calendar', '0014_representativebooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_bookings', to='leads.record')),
                ('companys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
                ('employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_bookings', to=settings.AUTH_USER_MODEL)),
                ('felial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='felial.felial')),
                ('registrar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_booking_registrar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
