# Generated by Django 5.1.4 on 2025-01-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0017_remove_historicalrecord_caunt_remove_record_caunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.record')),
            ],
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.cost')),
            ],
        ),
    ]
