# Generated by Django 5.1.4 on 2025-01-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_cost_record'),
        ('leads', '0019_remove_historicalrecord_cost_remove_record_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surcharge',
            name='cost',
        ),
        migrations.AddField(
            model_name='surcharge',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.record'),
        ),
    ]
