# Generated by Django 5.1.4 on 2025-01-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_remove_surcharge_cost_surcharge_record'),
        ('leads', '0019_remove_historicalrecord_cost_remove_record_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.record'),
        ),
    ]
