# Generated by Django 5.1.4 on 2025-03-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_alter_surcharge_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surcharge',
            old_name='surcharge',
            new_name='cost',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
