# Generated by Django 5.1.4 on 2025-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0006_rename_surcharge_surcharge_cost_delete_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
