# Generated by Django 5.1.4 on 2025-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0008_alter_surcharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
