# Generated by Django 5.1.4 on 2025-03-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0009_alter_surcharge_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surcharge',
            old_name='date',
            new_name='dat',
        ),
    ]
