# Generated by Django 5.1.4 on 2025-01-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
            preserve_default=False,
        ),
    ]
