# Generated by Django 5.1.4 on 2025-02-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_companys'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
    ]
