# Generated by Django 5.1.4 on 2025-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_felial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bet',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='percent',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_zp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
