# Generated by Django 5.1.4 on 2025-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bet_user_percent_user_type_zp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bet',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
    ]
