# Generated by Django 5.1.4 on 2025-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_bet_alter_user_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bet',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='percent',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
