# Generated by Django 5.1.4 on 2025-02-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('leads', '0023_record_felial_alter_record_companys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.record'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
