# Generated by Django 4.1.1 on 2024-12-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_record_coming'),
        ('coming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coming',
            name='lead',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coming', to='leads.record'),
        ),
    ]
