# Generated by Django 5.1.4 on 2024-12-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coming', '0003_alter_coming_date'),
        ('leads', '0009_remove_record_coming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='lead',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coming', to='leads.record'),
        ),
    ]
