# Generated by Django 5.1.4 on 2025-02-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cites', models.CharField(default=None, max_length=50, null=True)),
                ('title', models.CharField(default=None, max_length=50, null=True)),
                ('companys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
    ]
